// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uvghvyrvrsmyydpnobkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2Z2h2eXJ2cnNteXlkcG5vYmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNDQ3MjYsImV4cCI6MjA3MzgyMDcyNn0.sCBGUQgRI9AHhu1hJrmTp8CoGUTjzved_4p6XPVA5Z0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);